/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Chen
 */
public class PanelAnnouncement extends javax.swing.JPanel {

    /**
     * Creates new form PanelAnnouncement
     */
    public PanelAnnouncement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel7.setBackground(new java.awt.Color(220, 220, 220));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Oswald Regular", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 84, 38));
        jLabel10.setText("May 9, 2018");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 90, 40));

        jPanel10.setBackground(new java.awt.Color(207, 207, 207));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(38, 48, 58));
        jLabel12.setFont(new java.awt.Font("Oswald Regular", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(38, 48, 58));
        jLabel12.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mollis pulvinar porta. Integer ultrices ante quam, ac porttitor ipsum aliquam sit amet. Nam sit amet urna pretium, mattis quam sed, commodo ante.");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 900, 40));

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1010, 60));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img-user1.png"))); // NOI18N
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 70));

        jLabel22.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(38, 48, 58));
        jLabel22.setText("Jane Doe");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, 70));

        add(jPanel7);
        jPanel7.setBounds(60, 40, 1010, 200);

        jPanel8.setBackground(new java.awt.Color(220, 220, 220));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img-user1.png"))); // NOI18N
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        jLabel5.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 48, 58));
        jLabel5.setText("Tom Perry");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, 70));

        jLabel9.setFont(new java.awt.Font("Oswald Regular", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 84, 38));
        jLabel9.setText("April 12, 2018");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, 90, 40));

        jPanel9.setBackground(new java.awt.Color(207, 207, 207));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Oswald Regular", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(38, 48, 58));
        jLabel13.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mollis pulvinar porta. Integer ultrices ante quam, ac porttitor ipsum aliquam sit amet. Nam sit amet urna pretium, mattis quam sed, commodo ante.");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 910, 60));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1010, 70));

        add(jPanel8);
        jPanel8.setBounds(60, 270, 1010, 210);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
