/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Chen
 */
public class PanelHome extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogin
     */
    public PanelHome() {
        initComponents();
        panelLoginForm.setVisible(false);
    }

    public JButton getBtnLogin() {
        return btnLogin;
    }

    public void setBtnLogin(JButton btnLogin) {
        this.btnLogin = btnLogin;
    }

    public JPasswordField getTxtFldPassword() {
        return txtFldPassword;
    }

    public void setTxtFldPassword(JPasswordField txtFldPassword) {
        this.txtFldPassword = txtFldPassword;
    }

    public JTextField getTxtFldUsername() {
        return txtFldUsername;
    }

    public void setTxtFldUsername(JTextField txtFldUsername) {
        this.txtFldUsername = txtFldUsername;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        panelHomeRight = new javax.swing.JPanel();
        panelLoginForm = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFldUsername = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtFldPassword = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(47, 55, 66));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(47, 55, 66));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 420, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 250, 10));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnLogin.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 100, 40));

        jPanel2.setBackground(new java.awt.Color(255, 84, 38));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Oswald Regular", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lorem ipsum dolor sit amet, consectetur ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 10, 400, 40);

        jLabel2.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Nam mollis pulvinar porta. Integer ultrices ante quam, ac ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 50, 380, 25);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 480, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mollis pulvinar porta. Integer ultrices ante quam, ac porttitor ipsum aliquam sit amet. Nam sit amet urna pretium, mattis quam sed, commodo ante.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 460, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mollis pulvinar porta. Integer ultrices ante quam, ac porttitor ipsum aliquam sit amet. Nam sit amet urna pretium, mattis quam sed, commodo ante.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 440, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mollis pulvinar porta. Integer ultrices ante quam, ac porttitor ipsum aliquam sit amet. Nam sit amet urna pretium, mattis quam sed, commodo ante.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 450, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mollis pulvinar porta. Integer ultrices ante quam, ac porttitor ipsum aliquam sit amet. Nam sit amet urna pretium, mattis quam sed, commodo ante.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 460, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mollis pulvinar porta. Integer ultrices ante quam, ac porttitor ipsum aliquam sit amet. Nam sit amet urna pretium, mattis quam sed, commodo ante.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 450, 50));

        add(jPanel1);
        jPanel1.setBounds(30, 120, 570, 630);

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("INSERT LOGO HERE");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(60, 30, 220, 14);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnCloseWhite.png"))); // NOI18N
        btnClose.setContentAreaFilled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnClose);
        btnClose.setBounds(1270, 0, 100, 70);

        add(jPanel3);
        jPanel3.setBounds(0, 0, 1370, 70);

        panelHomeRight.setBackground(new java.awt.Color(47, 55, 66));
        panelHomeRight.setOpaque(false);
        panelHomeRight.setPreferredSize(new java.awt.Dimension(100, 190));
        panelHomeRight.setLayout(null);

        panelLoginForm.setBackground(new java.awt.Color(255, 255, 255));
        panelLoginForm.setMinimumSize(new java.awt.Dimension(300, 480));
        panelLoginForm.setPreferredSize(new java.awt.Dimension(300, 480));
        panelLoginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Oswald Regular", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(38, 48, 58));
        jLabel10.setText("LOGIN");
        panelLoginForm.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 190, 60));

        jLabel11.setFont(new java.awt.Font("Oswald Regular", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(38, 48, 58));
        jLabel11.setText("USERNAME");
        panelLoginForm.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 180, 40));

        txtFldUsername.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        txtFldUsername.setBorder(null);
        txtFldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldUsernameActionPerformed(evt);
            }
        });
        panelLoginForm.add(txtFldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 350, 40));

        jSeparator4.setBackground(new java.awt.Color(38, 48, 58));
        panelLoginForm.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 360, 20));

        jLabel12.setFont(new java.awt.Font("Oswald Regular", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(38, 48, 58));
        jLabel12.setText("PASSWORD");
        panelLoginForm.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 180, 40));

        txtFldPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFldPassword.setForeground(new java.awt.Color(38, 48, 58));
        txtFldPassword.setBorder(null);
        panelLoginForm.add(txtFldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 360, 30));

        jSeparator3.setBackground(new java.awt.Color(38, 48, 58));
        panelLoginForm.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 360, 50));

        btnLogin.setBackground(new java.awt.Color(255, 84, 38));
        btnLogin.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(36, 47, 65));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnLoginBig.png"))); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelLoginForm.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 370, 50));

        jPanel4.setBackground(new java.awt.Color(255, 84, 38));
        panelLoginForm.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 30, 70));

        panelHomeRight.add(panelLoginForm);
        panelLoginForm.setBounds(40, 110, 470, 530);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img_card.png"))); // NOI18N
        panelHomeRight.add(jLabel6);
        jLabel6.setBounds(-90, 0, 610, 700);

        add(panelHomeRight);
        panelHomeRight.setBounds(730, 130, 520, 640);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //PanelLogin pl = new PanelLogin();
        panelLoginForm.setVisible(true);

        panelHomeRight.removeAll();
        panelHomeRight.repaint();
        panelHomeRight.revalidate();

        panelHomeRight.setLayout(new java.awt.BorderLayout());
        panelHomeRight.add(panelLoginForm);
        panelHomeRight.repaint();
        panelHomeRight.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        PanelLanding ph = new PanelLanding();
        this.removeAll();
        this.repaint();
        this.revalidate();

        this.setLayout(new java.awt.BorderLayout());
        this.add(ph);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel panelHomeRight;
    private javax.swing.JPanel panelLoginForm;
    private javax.swing.JPasswordField txtFldPassword;
    private javax.swing.JTextField txtFldUsername;
    // End of variables declaration//GEN-END:variables
}
