/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Chen
 */
public class PanelUserManagement extends javax.swing.JPanel {

    /**
     * Creates new form PanelUserManagement
     */
    public PanelUserManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelAddProduct = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblProductHeader = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtFldUserType = new javax.swing.JTextField();
        txtFldName = new javax.swing.JTextField();
        txtFldStatus = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 62, 71)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User ID", "Name", "Status", "User Type"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 540, 510));

        panelAddProduct.setBackground(new java.awt.Color(220, 220, 220));
        panelAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        panelAddProduct.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(53, 62, 71));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelAddProduct.add(jPanel2);
        jPanel2.setBounds(0, 20, 30, 70);

        lblProductHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblProductHeader.setFont(new java.awt.Font("Oswald Regular", 0, 24)); // NOI18N
        lblProductHeader.setForeground(new java.awt.Color(53, 62, 71));
        lblProductHeader.setText("Add User");
        panelAddProduct.add(lblProductHeader);
        lblProductHeader.setBounds(50, 30, 186, 47);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(53, 62, 71));
        jLabel2.setText("User Type");
        panelAddProduct.add(jLabel2);
        jLabel2.setBounds(50, 330, 110, 30);
        panelAddProduct.add(jSeparator1);
        jSeparator1.setBounds(50, 410, 250, 10);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 62, 71));
        jLabel3.setText("Name");
        panelAddProduct.add(jLabel3);
        jLabel3.setBounds(50, 120, 110, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 62, 71));
        jLabel4.setText("Status");
        panelAddProduct.add(jLabel4);
        jLabel4.setBounds(50, 220, 160, 30);
        panelAddProduct.add(jSeparator2);
        jSeparator2.setBounds(50, 200, 250, 20);
        panelAddProduct.add(jSeparator3);
        jSeparator3.setBounds(50, 300, 250, 20);

        txtFldUserType.setBackground(new java.awt.Color(220, 220, 220));
        txtFldUserType.setBorder(null);
        panelAddProduct.add(txtFldUserType);
        txtFldUserType.setBounds(50, 370, 250, 30);

        txtFldName.setBackground(new java.awt.Color(220, 220, 220));
        txtFldName.setBorder(null);
        txtFldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldNameActionPerformed(evt);
            }
        });
        panelAddProduct.add(txtFldName);
        txtFldName.setBounds(50, 160, 250, 30);

        txtFldStatus.setBackground(new java.awt.Color(220, 220, 220));
        txtFldStatus.setBorder(null);
        panelAddProduct.add(txtFldStatus);
        txtFldStatus.setBounds(50, 260, 250, 30);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnSave.png"))); // NOI18N
        panelAddProduct.add(btnSave);
        btnSave.setBounds(60, 440, 240, 40);

        add(panelAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 11, 360, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        lblProductHeader.setText("Update User");
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1KeyPressed

    private void txtFldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblProductHeader;
    private javax.swing.JPanel panelAddProduct;
    private javax.swing.JTextField txtFldName;
    private javax.swing.JTextField txtFldStatus;
    private javax.swing.JTextField txtFldUserType;
    // End of variables declaration//GEN-END:variables
}
