/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Chen
 */
public class PanelCanteenInventory extends javax.swing.JPanel {

    /**
     * Creates new form PanelCanteen
     */
    public PanelCanteenInventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelAddProduct = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblProductHeader = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtFldProdPrice = new javax.swing.JTextField();
        txtFldProdName = new javax.swing.JTextField();
        txtFldProdQuantity = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 62, 71)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Product Quantity", "Product Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 10, 540, 510);

        panelAddProduct.setBackground(new java.awt.Color(220, 220, 220));
        panelAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        panelAddProduct.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(53, 62, 71));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelAddProduct.add(jPanel2);
        jPanel2.setBounds(0, 20, 30, 70);

        lblProductHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblProductHeader.setFont(new java.awt.Font("Oswald Regular", 0, 24)); // NOI18N
        lblProductHeader.setForeground(new java.awt.Color(53, 62, 71));
        lblProductHeader.setText("Add Product");
        panelAddProduct.add(lblProductHeader);
        lblProductHeader.setBounds(50, 30, 186, 47);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(53, 62, 71));
        jLabel2.setText("Product Price");
        panelAddProduct.add(jLabel2);
        jLabel2.setBounds(50, 330, 110, 30);
        panelAddProduct.add(jSeparator1);
        jSeparator1.setBounds(50, 410, 250, 10);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 62, 71));
        jLabel3.setText("Product Name");
        panelAddProduct.add(jLabel3);
        jLabel3.setBounds(50, 120, 110, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 62, 71));
        jLabel4.setText("Product Quantity");
        panelAddProduct.add(jLabel4);
        jLabel4.setBounds(50, 220, 160, 30);
        panelAddProduct.add(jSeparator2);
        jSeparator2.setBounds(50, 200, 250, 20);
        panelAddProduct.add(jSeparator3);
        jSeparator3.setBounds(50, 300, 250, 20);

        txtFldProdPrice.setBackground(new java.awt.Color(220, 220, 220));
        txtFldProdPrice.setBorder(null);
        panelAddProduct.add(txtFldProdPrice);
        txtFldProdPrice.setBounds(50, 370, 250, 30);

        txtFldProdName.setBackground(new java.awt.Color(220, 220, 220));
        txtFldProdName.setBorder(null);
        txtFldProdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldProdNameActionPerformed(evt);
            }
        });
        panelAddProduct.add(txtFldProdName);
        txtFldProdName.setBounds(50, 160, 250, 30);

        txtFldProdQuantity.setBackground(new java.awt.Color(220, 220, 220));
        txtFldProdQuantity.setBorder(null);
        panelAddProduct.add(txtFldProdQuantity);
        txtFldProdQuantity.setBounds(50, 260, 250, 30);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnSave.png"))); // NOI18N
        panelAddProduct.add(btnSave);
        btnSave.setBounds(60, 440, 240, 40);

        jPanel1.add(panelAddProduct);
        panelAddProduct.setBounds(650, 10, 360, 510);

        add(jPanel1);
        jPanel1.setBounds(30, 30, 1130, 541);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFldProdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldProdNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldProdNameActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
       lblProductHeader.setText("Update Product");

    }//GEN-LAST:event_jTable1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblProductHeader;
    private javax.swing.JPanel panelAddProduct;
    private javax.swing.JTextField txtFldProdName;
    private javax.swing.JTextField txtFldProdPrice;
    private javax.swing.JTextField txtFldProdQuantity;
    // End of variables declaration//GEN-END:variables
}
