/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JLabel;

/**
 *
 * @author Chen
 */
public class PanelProfile extends javax.swing.JPanel {

    /**
     * Creates new form PanelProfile
     */
    public PanelProfile() {
        initComponents();
    }

    public JLabel getLblAddress() {
        return lblAddress;
    }

    public void setLblAddress(JLabel lblAddress) {
        this.lblAddress = lblAddress;
    }

    public JLabel getLblBirthdate() {
        return lblBirthdate;
    }

    public void setLblBirthdate(JLabel lblBirthdate) {
        this.lblBirthdate = lblBirthdate;
    }

    public JLabel getLblGender() {
        return lblGender;
    }

    public void setLblGender(JLabel lblGender) {
        this.lblGender = lblGender;
    }

    public JLabel getLblName() {
        return lblName;
    }

    public void setLblName(JLabel lblName) {
        this.lblName = lblName;
    }

    public JLabel getLblUserPhoto() {
        return lblUserPhoto;
    }

    public void setLblUserPhoto(JLabel lblUserPhoto) {
        this.lblUserPhoto = lblUserPhoto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        lblTextBday = new javax.swing.JLabel();
        lblTextName = new javax.swing.JLabel();
        lblTextAdd = new javax.swing.JLabel();
        lblTextGender = new javax.swing.JLabel();
        lblBirthdate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblUserPhoto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel7.setBackground(new java.awt.Color(236, 235, 235));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextBday.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        lblTextBday.setForeground(new java.awt.Color(38, 48, 58));
        lblTextBday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextBday.setText("Birthdate");
        jPanel7.add(lblTextBday, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 130, 50));

        lblTextName.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        lblTextName.setForeground(new java.awt.Color(38, 48, 58));
        lblTextName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextName.setText("Name");
        jPanel7.add(lblTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 130, 50));

        lblTextAdd.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        lblTextAdd.setForeground(new java.awt.Color(38, 48, 58));
        lblTextAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextAdd.setText("Address");
        jPanel7.add(lblTextAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 130, 50));

        lblTextGender.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        lblTextGender.setForeground(new java.awt.Color(38, 48, 58));
        lblTextGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextGender.setText("Gender");
        jPanel7.add(lblTextGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 130, 50));

        lblBirthdate.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        lblBirthdate.setForeground(new java.awt.Color(38, 48, 58));
        lblBirthdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBirthdate.setText("May 12, 1990");
        jPanel7.add(lblBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 130, 50));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 280, 20));
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 280, 20));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 280, 20));
        jPanel7.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 280, 20));

        lblName.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(38, 48, 58));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Jane Doe");
        jPanel7.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 130, 50));

        lblAddress.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(38, 48, 58));
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddress.setText("New York");
        jPanel7.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 130, 50));

        lblGender.setFont(new java.awt.Font("Oswald Regular", 0, 18)); // NOI18N
        lblGender.setForeground(new java.awt.Color(38, 48, 58));
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGender.setText("Female");
        jPanel7.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 130, 50));

        lblUserPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img_user2.png"))); // NOI18N
        jPanel7.add(lblUserPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 280, 280));

        jPanel1.setBackground(new java.awt.Color(47, 55, 66));

        jPanel2.setBackground(new java.awt.Color(47, 55, 66));
        jPanel1.add(jPanel2);

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 20, 70));

        jPanel3.setBackground(new java.awt.Color(47, 55, 66));
        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 20, 70));

        add(jPanel7);
        jPanel7.setBounds(150, 90, 820, 380);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTextAdd;
    private javax.swing.JLabel lblTextBday;
    private javax.swing.JLabel lblTextGender;
    private javax.swing.JLabel lblTextName;
    private javax.swing.JLabel lblUserPhoto;
    // End of variables declaration//GEN-END:variables
}
